export const products = [
  {
    id: 1,
    slug: "acana-duck-pear-dog-treats",
    name: "ACANA Duck & Pear Dog Treats",
    category: "dogs",
    categoryLabel: "Dogs",
    type: "Treats",
    price: 14.99,
    oldPrice: 19.99,
    badge: "Popular",
    emoji: "🦴",
    description:
      "Limited ingredient dog treats made with quality animal ingredients and a delicious duck and pear recipe.",
  },
  {
    id: 2,
    slug: "stella-chewys-chicken-dog-treats",
    name: "Stella & Chewy's Chicken Dog Treats",
    category: "dogs",
    categoryLabel: "Dogs",
    type: "Treats",
    price: 12.99,
    oldPrice: 17.99,
    badge: "Best Seller",
    emoji: "🐶",
    description:
      "Freeze-dried chicken treats made for rewarding your dog during training or everyday moments.",
  },
  {
    id: 3,
    slug: "bixbi-hip-joint-beef-liver",
    name: "BIXBI Hip & Joint Beef Liver Jerky",
    category: "dogs",
    categoryLabel: "Dogs",
    type: "Treats",
    price: 16.99,
    oldPrice: 21.99,
    badge: "Sale",
    emoji: "🥩",
    description:
      "A tasty beef liver jerky treat designed for happy and active dogs.",
  },
  {
    id: 4,
    slug: "bocces-bacn-nutty-training-bites",
    name: "Bocce's Bac'n Nutty Training Bites",
    category: "dogs",
    categoryLabel: "Dogs",
    type: "Training Treats",
    price: 9.99,
    oldPrice: null,
    badge: null,
    emoji: "🥓",
    description:
      "Small training bites with a delicious bacon and peanut butter inspired flavor.",
  },

  {
    id: 5,
    slug: "applaws-chicken-breast-broth",
    name: "Applaws Chicken Breast in Broth",
    category: "cats",
    categoryLabel: "Cats",
    type: "Wet Food",
    price: 11.99,
    oldPrice: 15.99,
    badge: "Popular",
    emoji: "🐱",
    description:
      "Natural wet cat food featuring chicken breast in a flavorful broth.",
  },
  {
    id: 6,
    slug: "applaws-chicken-pumpkin-broth",
    name: "Applaws Chicken Breast with Pumpkin",
    category: "cats",
    categoryLabel: "Cats",
    type: "Wet Food",
    price: 12.49,
    oldPrice: null,
    badge: null,
    emoji: "🎃",
    description:
      "A flavorful wet food recipe combining chicken breast with pumpkin in broth.",
  },
  {
    id: 7,
    slug: "applaws-tuna-seaweed-broth",
    name: "Applaws Tuna Fillet with Seaweed",
    category: "cats",
    categoryLabel: "Cats",
    type: "Wet Food",
    price: 13.99,
    oldPrice: 17.99,
    badge: "New",
    emoji: "🐟",
    description:
      "Tuna fillet with seaweed in broth, created as a tasty meal option for cats.",
  },
  {
    id: 8,
    slug: "whisker-city-cat-bed",
    name: "Whisker City Cozy Cat Bed",
    category: "cats",
    categoryLabel: "Cats",
    type: "Accessories",
    price: 32.99,
    oldPrice: null,
    badge: null,
    emoji: "🛏️",
    description:
      "A soft and comfortable resting space designed for cats.",
  },

  {
    id: 9,
    slug: "full-cheeks-small-pet-mix",
    name: "Full Cheeks Small Pet Food Mix",
    category: "small",
    categoryLabel: "Small Pets",
    type: "Food",
    price: 12.99,
    oldPrice: 16.99,
    badge: "Sale",
    emoji: "🐹",
    description:
      "A tasty food mix suitable for small companion animals.",
  },
  {
    id: 10,
    slug: "rabbit-comfort-bedding",
    name: "Rabbit Comfort Bedding",
    category: "small",
    categoryLabel: "Small Pets",
    type: "Accessories",
    price: 10.99,
    oldPrice: null,
    badge: null,
    emoji: "🐰",
    description:
      "Soft bedding designed to create a comfortable space for small pets.",
  },
  {
    id: 11,
    slug: "hamster-play-tunnel",
    name: "Hamster Play Tunnel",
    category: "small",
    categoryLabel: "Small Pets",
    type: "Toys",
    price: 8.99,
    oldPrice: null,
    badge: "New",
    emoji: "🐹",
    description:
      "An interactive tunnel for curious hamsters and other small pets.",
  },

  {
    id: 12,
    slug: "aqueon-betta-pellets",
    name: "Aqueon Betta Color Enhancing Pellets",
    category: "fish",
    categoryLabel: "Fish",
    type: "Food",
    price: 9.99,
    oldPrice: 13.99,
    badge: "Popular",
    emoji: "🐠",
    description:
      "Fish food pellets designed for bettas and other suitable aquarium fish.",
  },
  {
    id: 13,
    slug: "api-freshwater-aquarium-test-kit",
    name: "API Freshwater Aquarium Master Test Kit",
    category: "fish",
    categoryLabel: "Fish",
    type: "Aquarium Care",
    price: 29.49,
    oldPrice: null,
    badge: null,
    emoji: "🧪",
    description:
      "An aquarium water testing kit for monitoring important freshwater parameters.",
  },
  {
    id: 14,
    slug: "aquarium-plant-decoration",
    name: "Aquarium Plant Decoration",
    category: "fish",
    categoryLabel: "Fish",
    type: "Accessories",
    price: 14.99,
    oldPrice: null,
    badge: "New",
    emoji: "🌿",
    description:
      "Decorative aquarium greenery for creating an attractive underwater environment.",
  },

  {
    id: 15,
    slug: "reptile-terrarium-starter",
    name: "Reptile Terrarium Starter Kit",
    category: "reptile",
    categoryLabel: "Reptiles",
    type: "Terrariums",
    price: 49.99,
    oldPrice: 59.99,
    badge: "Sale",
    emoji: "🦎",
    description:
      "A practical starter setup for creating a comfortable reptile habitat.",
  },
  {
    id: 16,
    slug: "reptile-heating-lamp",
    name: "Reptile Heating Lamp",
    category: "reptile",
    categoryLabel: "Reptiles",
    type: "Heating",
    price: 24.99,
    oldPrice: null,
    badge: null,
    emoji: "💡",
    description:
      "Heating equipment designed for suitable reptile habitats.",
  },

  {
    id: 17,
    slug: "wild-bird-food-mix",
    name: "Wild Bird Food Mix",
    category: "bird",
    categoryLabel: "Birds",
    type: "Food",
    price: 13.99,
    oldPrice: 17.99,
    badge: "Popular",
    emoji: "🦜",
    description:
      "A convenient food mix for a variety of wild and companion birds.",
  },
  {
    id: 18,
    slug: "bird-cage-accessory-kit",
    name: "Bird Cage Accessory Kit",
    category: "bird",
    categoryLabel: "Birds",
    type: "Accessories",
    price: 18.99,
    oldPrice: null,
    badge: null,
    emoji: "🐦",
    description:
      "Useful accessories for creating a more engaging bird habitat.",
  },
];